spring:
  application:
    name: order-service
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
  servlet:
    context-path: /api

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.es.orderservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized
